<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-08-10T07:40:09 IST" name="ParallelTestSuite" finished-at="2023-08-10T07:41:11 IST" duration-ms="61418">
    <groups>
      <group name="sanity">
        <method signature="BrowseFacebookStep.testFBLoginFeature()[pri:0, instance:UI.step.BrowseFacebookStep@5b619d14]" name="testFBLoginFeature" class="UI.step.BrowseFacebookStep"/>
        <method signature="TestNgGrouping.teatSanity()[pri:0, instance:UI.step.TestNgGrouping@1f6c9cd8]" name="teatSanity" class="UI.step.TestNgGrouping"/>
      </group> <!-- sanity -->
    </groups>
    <test started-at="2023-08-10T07:40:09 IST" name="ParallelTest" finished-at="2023-08-10T07:41:11 IST" duration-ms="61418">
      <class name="UI.step.BrowseFacebookStep">
        <test-method is-config="true" signature="lunchBrowser(org.testng.ITestContext, java.lang.String)[pri:0, instance:UI.step.BrowseFacebookStep@5b619d14]" started-at="2023-08-10T07:40:09 IST" name="lunchBrowser" finished-at="2023-08-10T07:40:18 IST" duration-ms="8605" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@67ec8477]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lunchBrowser -->
        <test-method signature="testFBLoginFeature()[pri:0, instance:UI.step.BrowseFacebookStep@5b619d14]" started-at="2023-08-10T07:40:18 IST" name="testFBLoginFeature" finished-at="2023-08-10T07:40:32 IST" duration-ms="14034" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [sumit] but found [ram]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [sumit] but found [ram]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at UI.step.BrowseFacebookStep.testFBLoginFeature(BrowseFacebookStep.java:20)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFBLoginFeature -->
        <test-method is-config="true" signature="checkStatus(org.testng.ITestResult)[pri:0, instance:UI.step.BrowseFacebookStep@5b619d14]" started-at="2023-08-10T07:40:32 IST" name="checkStatus" finished-at="2023-08-10T07:40:33 IST" duration-ms="669" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testFBLoginFeature status=FAILURE method=BrowseFacebookStep.testFBLoginFeature()[pri:0, instance:UI.step.BrowseFacebookStep@5b619d14] output={null}]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "com.aventstack.extentreports.ExtentTest.fail(java.lang.Throwable)" because "UI.BaseClass.extentTest" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentTest.fail(java.lang.Throwable)" because "UI.BaseClass.extentTest" is null
at UI.BaseClass.checkStatus(BaseClass.java:76)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:340)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:294)
at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:683)
at org.testng.internal.TestInvoker.runAfterGroupsConfigurations(TestInvoker.java:658)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:642)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkStatus -->
        <test-method is-config="true" signature="quitQuit()[pri:0, instance:UI.step.BrowseFacebookStep@5b619d14]" started-at="2023-08-10T07:40:33 IST" name="quitQuit" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1691633433409" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitQuit -->
      </class> <!-- UI.step.BrowseFacebookStep -->
      <class name="UI.step.TestNgGrouping">
        <test-method is-config="true" signature="lunchBrowser(org.testng.ITestContext, java.lang.String)[pri:0, instance:UI.step.TestNgGrouping@1f6c9cd8]" started-at="2023-08-10T07:40:09 IST" name="lunchBrowser" finished-at="2023-08-10T07:40:19 IST" duration-ms="9100" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@67ec8477]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lunchBrowser -->
        <test-method signature="teatSanity()[pri:0, instance:UI.step.TestNgGrouping@1f6c9cd8]" started-at="2023-08-10T07:40:19 IST" name="teatSanity" finished-at="2023-08-10T07:41:08 IST" duration-ms="49760" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at UI.step.TestNgGrouping.teatSanity(TestNgGrouping.java:19)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teatSanity -->
        <test-method is-config="true" signature="checkStatus(org.testng.ITestResult)[pri:0, instance:UI.step.TestNgGrouping@1f6c9cd8]" started-at="2023-08-10T07:41:08 IST" name="checkStatus" finished-at="2023-08-10T07:41:11 IST" duration-ms="2265" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=teatSanity status=FAILURE method=TestNgGrouping.teatSanity()[pri:0, instance:UI.step.TestNgGrouping@1f6c9cd8] output={null}]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "com.aventstack.extentreports.ExtentTest.fail(java.lang.Throwable)" because "UI.BaseClass.extentTest" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentTest.fail(java.lang.Throwable)" because "UI.BaseClass.extentTest" is null
at UI.BaseClass.checkStatus(BaseClass.java:76)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:340)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:294)
at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:683)
at org.testng.internal.TestInvoker.runAfterGroupsConfigurations(TestInvoker.java:658)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:642)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkStatus -->
        <test-method is-config="true" signature="quitQuit()[pri:0, instance:UI.step.TestNgGrouping@1f6c9cd8]" started-at="2023-08-10T07:41:11 IST" name="quitQuit" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1691633471130" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitQuit -->
      </class> <!-- UI.step.TestNgGrouping -->
    </test> <!-- ParallelTest -->
  </suite> <!-- ParallelTestSuite -->
</testng-results>
